# Site settings
title: Italy
description: >
  Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.
baseurl: "/italy" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]

campaign-link: italia-link
